blog-controllers:
    resource:
        path: ../src/Blog/Transport/Controller/Api/
        namespace: App\Blog\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

blog-public-controllers:
    resource:
        path: ../src/Blog/Transport/Controller/Frontend/
        namespace: App\Blog\Transport\Controller\Frontend
    type: attribute
    prefix: /
    defaults:
        _format: json
