notification-controllers:
    resource:
        path: ../src/Notification/Transport/Controller/Api/
        namespace: App\Notification\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json
